# =======================================================================
# QUARKUS CONFIGURATION - MOVIE SERVICE
# =======================================================================

# --- API ROUTING ---
# Para no usar PathRewrite en el Gateway, el servicio expone su API en:
quarkus.http.root-path=/api/v1
quarkus.http.port=8082

# --- DATASOURCE (POSTGRESQL) ---
quarkus.datasource.db-kind=postgresql
# Asumimos que PostgreSQL expone el puerto 5433 localmente (Docker Compose del monorepo)
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/db_movies
quarkus.datasource.username=postgres
quarkus.datasource.password=root

# --- HIBERNATE ORM ---
# Flyway maneja la base de datos, Hibernate no debe modificar el esquema
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.format-sql=true

# --- FLYWAY MIGRATIONS ---
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db/migration
quarkus.flyway.baseline-on-migrate=true

# --- REDIS CACHE ---
# Comentado temporalmente hasta levantar Redis en Docker, Quarkus usará Dev Services si no lo encuentra.
# quarkus.redis.hosts=redis://localhost:6379

# --- TMDB REST CLIENT ---
# URL base de la API externa
quarkus.rest-client.tmdb-api.url=https://api.themoviedb.org/3
# Variable de Entorno (Se inyecta en local via .env)
tmdb.api.key=${TMDB_API_KEY:default_test_key}
