### Registrar usuario exitosamente

POST http://localhost:3000/auth/register
Content-Type: application/json
{
  "email": "juan@utp.edu.pe",
  "contrasena": "password123",
  "nombres": "Juan",
  "apellidos": "Perez"
}

## login con credenciales validas
POST http://localhost:3000/auth/login
Content-Type: application/json
{
  "email": "juan@utp.edu.pe",
  "contrasena": "password123"
}


## Login con credenciales invalidas
POST http://localhost:3000/auth/login
Content-Type: application/json
{
  "email": "juan@utp.edu.pe",
  "contrasena": "password1234"
}

